name: Extract Fresh VLESS & VMess Links

on:
  push:
    paths:
      - 'configs/proxy_configs.txt'
  workflow_dispatch:

jobs:
  extract-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Extract fresh VLESS & VMess links (overwrite mode)
        run: |
          python3 << 'EOF'
import re

input_path = 'configs/proxy_configs.txt'
output_path = 'configs/vmess_vless.txt'

with open(input_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

valid = [line.strip() for line in lines if line.strip().startswith(('vmess://', 'vless://'))]

with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(valid))

print(f"{len(valid)} valid links saved to {output_path}")
EOF

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add configs/vmess_vless.txt
          git commit -m "Update vmess_vless.txt from proxy_configs.txt" || echo "No changes to commit"
          git push
