name: Extract VLESS & VMess Links

on:
  push:
    paths:
      - 'configs/proxy_configs.txt'
  workflow_dispatch:

jobs:
  extract-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extract VLESS & VMess links
        run: |
          mkdir -p configs
          python3 - <<EOF
import re
input_file = 'configs/proxy_configs.txt'
output_file = 'configs/vmess_vless.txt'

try:
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
except FileNotFoundError:
    print(f"{input_file} not found.")
    exit(1)

filtered = [line.strip() for line in lines if line.strip().startswith(('vmess://', 'vless://'))]

with open(output_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(filtered))

print(f"{len(filtered)} VLESS/VMess links written to {output_file}")
EOF

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add configs/vmess_vless.txt
          git commit -m "Auto-update VLESS/VMess links" || echo "No changes to commit"
          git push
