name: Fetch & Extract VLESS/VMess Links

on:
  schedule:
    - cron: '*/30 * * * *'  # هر ۳۰ دقیقه
  workflow_dispatch:         # اجرا دستی هم فعال
  push:                      # اجرای دستی در صورت نیاز

jobs:
  fetch-and-filter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download source file from GitHub
        run: |
          mkdir -p configs
          curl -sL https://raw.githubusercontent.com/10ium/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs.txt -o configs/proxy_configs.txt

      - name: Filter only VLESS/VMess links
        run: |
          echo "with open('configs/proxy_configs.txt', 'r', encoding='utf-8') as f:" > extract.py
          echo "    lines = f.readlines()" >> extract.py
          echo "filtered = [line.strip() for line in lines if line.strip().startswith(('vmess://', 'vless://'))]" >> extract.py
          echo "with open('configs/vmess_vless.txt', 'w', encoding='utf-8') as f:" >> extract.py
          echo "    f.write('\\n'.join(filtered))" >> extract.py
          echo "print(f'{len(filtered)} links written to vmess_vless.txt')" >> extract.py
          python3 extract.py

      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add configs/vmess_vless.txt
          git commit -m "Auto-update VLESS/VMess links" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
